name: Treiber-Checks
on: [push, pull_request]
jobs:
  driver-test:
    runs-on: ubuntu-latest
    steps:
      - name: Code abrufen
        uses: actions/checkout@v3
      - name: Prüfe Treiber-Module
        run: ./drivers/check_modules.sh
