name: Recovery System Tests
on: [push, pull_request]
jobs:
  recovery-test:
    runs-on: ubuntu-latest
    steps:
      - name: Code abrufen
        uses: actions/checkout@v3
      - name: Recovery prüfen
        run: ./recovery/recovery_check.sh
